import { v4 as uuid } from 'uuid';
import PlayingCard from '../components/PlayingCard';

const Blackjack = () => (
  <main className="flex-grow w-full bg-green-500">
    <h1>
      Welcome to Blackjack!
    </h1>
    <div className="flex flex-wrap">
      <PlayingCard
        id={uuid()}
        rank="A"
        suit="spades"
      />
      <PlayingCard
        id={uuid()}
        rank="2"
        suit="spades"
      />
      <PlayingCard
        id={uuid()}
        rank="3"
        suit="spades"
      />
      <PlayingCard
        id={uuid()}
        rank="4"
        suit="spades"
      />
      <PlayingCard
        id={uuid()}
        rank="5"
        suit="spades"
      />
      <PlayingCard
        id={uuid()}
        rank="6"
        suit="spades"
      />
      <PlayingCard
        id={uuid()}
        rank="7"
        suit="spades"
      />
      <PlayingCard
        id={uuid()}
        rank="8"
        suit="spades"
      />
      <PlayingCard
        id={uuid()}
        rank="9"
        suit="spades"
      />
      <PlayingCard
        id={uuid()}
        rank="10"
        suit="spades"
      />
      <PlayingCard
        id={uuid()}
        rank="J"
        suit="spades"
      />
      <PlayingCard
        id={uuid()}
        rank="Q"
        suit="spades"
      />
      <PlayingCard
        id={uuid()}
        rank="K"
        suit="spades"
      />
      <PlayingCard
        id={uuid()}
        rank="A"
        suit="clubs"
      />
      <PlayingCard
        id={uuid()}
        rank="2"
        suit="clubs"
      />
      <PlayingCard
        id={uuid()}
        rank="3"
        suit="clubs"
      />
      <PlayingCard
        id={uuid()}
        rank="4"
        suit="clubs"
      />
      <PlayingCard
        id={uuid()}
        rank="5"
        suit="clubs"
      />
      <PlayingCard
        id={uuid()}
        rank="6"
        suit="clubs"
      />
      <PlayingCard
        id={uuid()}
        rank="7"
        suit="clubs"
      />
      <PlayingCard
        id={uuid()}
        rank="8"
        suit="clubs"
      />
      <PlayingCard
        id={uuid()}
        rank="9"
        suit="clubs"
      />
      <PlayingCard
        id={uuid()}
        rank="10"
        suit="clubs"
      />
      <PlayingCard
        id={uuid()}
        rank="J"
        suit="clubs"
      />
      <PlayingCard
        id={uuid()}
        rank="Q"
        suit="clubs"
      />
      <PlayingCard
        id={uuid()}
        rank="K"
        suit="clubs"
      />
      <PlayingCard
        id={uuid()}
        rank="A"
        suit="hearts"
      />
      <PlayingCard
        id={uuid()}
        rank="2"
        suit="hearts"
      />
      <PlayingCard
        id={uuid()}
        rank="3"
        suit="hearts"
      />
      <PlayingCard
        id={uuid()}
        rank="4"
        suit="hearts"
      />
      <PlayingCard
        id={uuid()}
        rank="5"
        suit="hearts"
      />
      <PlayingCard
        id={uuid()}
        rank="6"
        suit="hearts"
      />
      <PlayingCard
        id={uuid()}
        rank="7"
        suit="hearts"
      />
      <PlayingCard
        id={uuid()}
        rank="8"
        suit="hearts"
      />
      <PlayingCard
        id={uuid()}
        rank="9"
        suit="hearts"
      />
      <PlayingCard
        id={uuid()}
        rank="10"
        suit="hearts"
      />
      <PlayingCard
        id={uuid()}
        rank="J"
        suit="hearts"
      />
      <PlayingCard
        id={uuid()}
        rank="Q"
        suit="hearts"
      />
      <PlayingCard
        id={uuid()}
        rank="K"
        suit="hearts"
      />
      <PlayingCard
        id={uuid()}
        rank="A"
        suit="diamonds"
      />
      <PlayingCard
        id={uuid()}
        rank="2"
        suit="diamonds"
      />
      <PlayingCard
        id={uuid()}
        rank="3"
        suit="diamonds"
      />
      <PlayingCard
        id={uuid()}
        rank="4"
        suit="diamonds"
      />
      <PlayingCard
        id={uuid()}
        rank="5"
        suit="diamonds"
      />
      <PlayingCard
        id={uuid()}
        rank="6"
        suit="diamonds"
      />
      <PlayingCard
        id={uuid()}
        rank="7"
        suit="diamonds"
      />
      <PlayingCard
        id={uuid()}
        rank="8"
        suit="diamonds"
      />
      <PlayingCard
        id={uuid()}
        rank="9"
        suit="diamonds"
      />
      <PlayingCard
        id={uuid()}
        rank="10"
        suit="diamonds"
      />
      <PlayingCard
        id={uuid()}
        rank="J"
        suit="diamonds"
      />
      <PlayingCard
        id={uuid()}
        rank="Q"
        suit="diamonds"
      />
      <PlayingCard
        id={uuid()}
        rank="K"
        suit="diamonds"
      />
      <PlayingCard
        id={uuid()}
        rank="JOK"
        suit="joker"
      />
    </div>
  </main>
);

export default Blackjack;
