name: Lint/Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: Dep-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      run: npm install --no-audit

    - name: Lint All Files
      run: npm run lint

    - name: Run All Tests
      run: npm run test
